fragment PostOverview on Post {
  id
  title
  createdAt
  apiDataBrief
  apiData
  heroImage {
    ...ImageData
  }
  og_image {
    ...ImageData
  }
}

fragment PostItem on Post {
  id
  title
  heroImage {
    ...ImageData
  }
}

fragment TopicPost on Post {
  id
  title
  apiDataBrief
  apiData
  heroImage {
    ...ImageData
  }
}

fragment RelatedPost on Post {
  id
  title
  heroImage {
    ...ImageData
  }
  og_image {
    ...ImageData
  }
  sections {
    name
    color
  }
}
