fragment PostOverview on Post {
  title
  createdAt
  apiDataBrief
  slug
  apiData
  heroImage {
    ...HeroImage
  }
  og_image {
    ...OgImage
  }
}

fragment PostItem on Post {
  title
  slug
  heroImage {
    ...HeroImage
  }
}
