fragment PostOverview on Post {
  title
  createdAt
  apiDataBrief
  slug
  apiData
  heroImage {
    ...ImageData
  }
  og_image {
    ...ImageData
  }
}

fragment PostItem on Post {
  title
  slug
  heroImage {
    ...ImageData
  }
}

fragment TopicPost on Post {
  title
  slug
  apiDataBrief
  apiData
  heroImage {
    ...ImageData
  }
}

fragment RelatedPost on Post {
  title
  slug
  heroImage {
    ...ImageData
  }
  og_image {
    ...ImageData
  }
  sections {
    name
    color
  }
}
