fragment LatestShorts on Video {
  id
  name
  uploader
  videoSrc
  heroImage {
    ...ImageData
  }
}

fragment ShortsData on Video {
  id
  state
  isShorts
  uploader
  videoSection
  tags(take: 1) {
    id
  }
}