query GetEditorChoices {
  editor: editorChoices(
    orderBy:  [
      { order: asc }
    ],
    take: 10,
    where: {
      state:  { equals: "published" }
    }
  ) {
    ...EditorChoiceData
  }
}