query GetLiveEventForHomepage($startDate: DateTime!, $endDate: DateTime!) {
  events(
    orderBy: [{ publishedDate: desc}],
    take: 1,
    where:  {
      eventType: { equals: "livestreaming" }
      state: { equals: "published" }
      startDate:  {
        lte: $startDate
      },
      OR: [
        {
          endDate:  {
            gt: $endDate
          }
        },
        {
          endDate:  {
             equals: null
          }
        }
      ]
    }
  ) {
    name
    link
    heroImage {
      ...ImageData
    }
  }
}