query GetExternalById($id: ID!) {
  external(where: { id: $id }) {
    id
    title
    thumb
    extend_byline
    publishedDate
    brief
    content
    tags {
      name
      slug
    }
  }
}

query GetRelatedPostsByExternalId($id: ID!) {
  external(where: { id: $id }) {
    relateds {
      ...RelatedPost
    }
  }
}
