query GetExternalById($id: ID!) {
  external(where: { id: $id }) {
    id
    title
    thumb
    publishedDate
    brief
    content
    tags {
      name
      slug
    }
    partner {
      name
      slug
    }
  }
}

query GetRelatedPostsByExternalId($id: ID!) {
  external(where: { id: $id }) {
    relateds {
      ...RelatedPost
    }
  }
}

query GetExternalsByPartnerSlug($skip: Int!, $take: Int!, $slug: String!) {
  externals(
    skip: $skip
    take: $take
    where: { partner: { slug: { equals: $slug } } }
    orderBy: { publishedDate: desc }
  ) {
    id
    title
    brief
    publishedDate
    thumb
  }
}
