query GetGames {
    games(
        take: 5
        orderBy: { sortOrder:  asc }
        where: { state: { equals: "published" } }
    ) {
        name
        descriptions
        link
        heroImage {
            ...HeroImage
        }
    }
}