query GetPostsBySectionSlug($skip: Int!, $take: Int, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: { sections: { some: { slug: { equals: $slug } } } }
    orderBy: { publishedDate: desc }
  ) {
    title
    createdAt
    brief
    heroImage {
      id
      resized {
        w1200
        w1600
        w2400
        w480
        w800
        original
      }
      resizedWebp {
        original
        w1200
        w1600
        w2400
        w480
        w800
      }
    }
    slug
  }
}

query GetPostsByCategorySlug($skip: Int!, $take: Int, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: { categories: { some: { slug: { equals: $slug } } } }
    orderBy: { publishedDate: desc }
  ) {
    title
    createdAt
    brief
    heroImage {
      id
      resized {
        w1200
        w1600
        w2400
        w480
        w800
        original
      }
      resizedWebp {
        original
        w1200
        w1600
        w2400
        w480
        w800
      }
    }
    slug
  }
}
