query GetPostsBySectionSlug($skip: Int!, $take: Int, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: { sections: { some: { slug: { equals: $slug } } } }
    orderBy: { publishedDate: desc }
  ) {
    title
    createdAt
    brief
    heroImage {
      ...HeroImage
    }
    slug
  }
}

query GetFlashNews {
  posts(
    take: 8
    orderBy: { publishedDate: desc }
    where: { state: { equals: "published" } }
  ) {
    title
    slug
  }
}

query GetPostsByCategorySlug($skip: Int!, $take: Int, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: { categories: { some: { slug: { equals: $slug } } } }
    orderBy: { publishedDate: desc }
  ) {
    title
    createdAt
    brief
    heroImage {
      ...HeroImage
    }
    slug
  }
}
