query GetPostsBySectionSlug($skip: Int!, $take: Int, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: {
      state: { equals: "published" }
      sections: { some: { slug: { equals: $slug } } }
    }
    orderBy: { publishedDate: desc }
  ) {
    ...PostOverview
  }
}

query GetFlashNews {
  posts(
    take: 8
    orderBy: { publishedDate: desc }
    where: { state: { equals: "published" } }
  ) {
    title
    slug
  }
}

query GetPostsByCategorySlug($skip: Int!, $take: Int, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: {
      state: { equals: "published" }
      categories: { some: { slug: { equals: $slug } } }
    }
    orderBy: { publishedDate: desc }
  ) {
    ...PostOverview
  }
}

query GetPostsByAuthorId($skip: Int!, $take: Int!, $id: ID!) {
  posts(
    skip: $skip
    take: $take
    where: {
      state: { equals: "published" }
      OR: [
        { writers: { some: { id: { equals: $id } } } }
        { photographers: { some: { id: { equals: $id } } } }
      ]
    }
    orderBy: { publishedDate: desc }
  ) {
    sections {
      name
      color
    }
    ...PostOverview
  }
}

query GetPostsByTagSlug($skip: Int!, $take: Int!, $slug: String!) {
  posts(
    skip: $skip
    take: $take
    where: {
      state: { equals: "published" }
      tags: { some: { slug: { equals: $slug } } }
    }
    orderBy: { publishedDate: desc }
  ) {
    sections {
      name
      color
    }
    ...PostOverview
  }
}

query GetPostBySlug($slug: String!) {
  post(where: { slug: $slug }) {
    slug
    title
    subtitle
    heroCaption
    publishedDate
    heroImage {
      ...HeroImage
    }
    og_image {
      ...OgImage
    }
    tags {
      slug
      name
    }
    sections {
      name
      color
    }
    writers {
      id
      name
    }
    photographers {
      id
      name
    }
    apiData
    apiDataBrief
  }
}

query GetRelatedPostsBySlug($slug: String!) {
  post(where: { slug: $slug }) {
    relateds {
      title
      createdAt
      slug
      heroImage {
        ...HeroImage
      }
      og_image {
        ...OgImage
      }
      sections {
        name
        color
      }
    }
  }
}
