query GetSectionsAndCategories {
  sections(
    orderBy: { order: asc },
    where: {
      state: { equals: "active" }
    }
  ) {
    name
    slug
    color
    categories(
      orderBy: { order: asc },
      where: {
        state: { equals: "active" }
      }
    ) {
      name
      slug
    }
  }
}