query GetTopics {
  topics(orderBy: { sortOrder: asc, id: desc }, where: { state: { equals: "published" } }) {
    name
    slug
    posts(
      take: 4
      orderBy: { publishedDate: desc }
      where: { state: { equals: "published" } }
    ) {
      ...PostItem
    }
  }
}

query GetTopicBasicInfo($slug: String!) {
  topic(where: { slug: $slug }) {
    slug
    name
    og_title # used by metatag
    apiDataBrief # used by metatag
    og_description # used by metatag
    state
    leading
    type
    style
    heroUrl
    heroVideo {
      state
      videoSrc
      heroImage {
        ...ImageData
      }
    }
    og_image { # used by metatag
      ...ImageData
    }
    heroImage {
      ...ImageData
    }
    slideshow_images {
      id
      name
      topicKeywords
      ...ImageData
    }
    manualOrderOfSlideshowImages
    tags { # used by `group` type
      id
      name
      slug
    }
  }
}

query GetListTypeTopcPosts($slug: String!, $take: Int!, $skip: Int = 0, $withAmount: Boolean! = false) {
  topic(where: { slug: $slug }) {
    posts(
      where: {
        state: { equals: "published" }
      },
      orderBy:  [
        { isFeatured: desc },
        { publishedDate: desc },
        { id: desc }
      ],
      take: $take,
      skip: $skip
    ) {
      ...TopicPost
    }
    postsCount(
      where: {
        state: { equals: "published" }
      }
    ) @include (if: $withAmount)
  }
}

query GetGroupTypeTopicPosts($slug: String!) {
  topic(where: { slug: $slug }) {
    posts(
      where: {
        state: { equals: "published" }
      },
      orderBy: [
        { isFeatured: desc },
        { publishedDate: desc },
        { id: desc }
      ]
    ) {
      ...TopicPost
      tags {
        id
      }
    }
  }
}