query GetLatestShorts($amount: Int!, $start: Int!) {
  news: videos(
    skip: $start,
    take: $amount,
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      isShorts:  {
         equals: true
      },
      videoSection: {
          equals: "news"
      }
    }) {
      ...LatestShorts
    }
  creativity: videos(
    skip: $start,
    take: $amount,
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      isShorts:  {
         equals: true
      },
      videoSection: {
          equals: "creativity"
      }
    }) {
      ...LatestShorts
    }
}

query GetShortsData($id: ID!) {
  video(where: {id: $id}) {
    ...ShortsData
  }
}

query GetShortsByTagAndVideoSection($tagId: ID!, $section: String!, $skip: Int = 0, $take: Int = 0) {
  videos(
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      videoSection:  {
        equals: $section
      }
      tags:  {
        some:  {
          id:  {
            equals: $tagId
          }
        }
      }
    }
    take: $take,
    skip: $skip,
  ) {
    ...LatestShorts
  }
}

query GetShortsByVideoSection($section: String!, $skip: Int = 0, $take: Int = 0) {
  videos(
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      videoSection:  {
        equals: $section
      }
    },
    take: $take,
    skip: $skip
  ) {
    ...LatestShorts
  }
}