query GetLatestShorts($amount: Int!) {
  news: videos(
    take: $amount,
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      videoSection: {
          equals: "news"
      }
    }) {
      ...LatestShorts
    }
  creativity: videos(
    take: $amount,
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      videoSection: {
          equals: "creativity"
      }
    }) {
      ...LatestShorts
    }
}

query GetShortsData($id: ID!) {
  video(where: {id: $id}) {
    ...ShortsData
  }
}

query GetShortsByTagAndVideoSection($tagId: ID!, $section: String!) {
  videos(
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      videoSection:  {
        equals: $section
      }
      tags:  {
        some:  {
          id:  {
            equals: $tagId
          }
        }
      }
    }
  ) {
    ...LatestShorts
  }
}

query GetShortsByVideoSection($section: String!) {
  videos(
    orderBy: { publishedDate: desc },
    where: {
      state: {
          equals: "published",
      },
      videoSection:  {
        equals: $section
      }
    }
  ) {
    ...LatestShorts
  }
}